language: ruby
rvm:
  - 2.3.1
notifications:
  webhooks:
    urls:
      - http://webhook.info/post/JNNSDORKJR
    on_start: always
services:
  - postgresql
before_script:
  - psql -c 'create database vent_api_test;' -U postgres
test:
  adapter: postgresql
  database: vent_api_test